import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar"
import Footer from './components/Footer'
import PrelineScript from "./components/PrelineScript"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harry_iconfy",
  description: "Generated by Harry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        <PrelineScript/>
    </html>
  );
}
